#!/usr/bin/bash
if systemctl cat -- uupd.timer &> /dev/null; then
    SERVICE="uupd.service"
else
    SERVICE="rpm-ostreed-automatic.service"
fi
if systemctl is-active --quiet "$SERVICE"; then
    echo "automatic updates are currently running, use \`journalctl -fexu $SERVICE\` to see logs"
    exit 1
fi
# rpm-ostree used due to bootc upgrade not supporting local layered packages
rpm-ostree upgrade
# Updates system Flatpaks
if flatpak remotes | grep -q system; then
    flatpak update -y
fi
# Update user Flatpaks
if flatpak remotes | grep -q user; then
    flatpak update --user -y
fi
# Guard Brew if the user does not own brew/doesn't exist
if [[ -O /var/home/linuxbrew/.linuxbrew/bin/brew ]]; then
    # Upgrade will run brew update if needed
    /var/home/linuxbrew/.linuxbrew/bin/brew upgrade
fi
